# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='blue_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blue_1', to='scoreboard.Player'),
        ),
        migrations.AlterField(
            model_name='team',
            name='blue_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blue_2', to='scoreboard.Player'),
        ),
        migrations.AlterField(
            model_name='team',
            name='red_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='red_1', to='scoreboard.Player'),
        ),
        migrations.AlterField(
            model_name='team',
            name='red_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='red_2', to='scoreboard.Player'),
        ),
    ]
