# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0002_auto_20160411_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='side',
            field=models.CharField(choices=[('blue', 'Blue'), ('red', 'Red')], default='blue', max_length=5),
            preserve_default=False,
        ),
    ]
