# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0003_goal_side'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='state',
            field=models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('waiting', 'Waiting'), ('ended', 'Ended')], default='waiting', max_length=15),
        ),
    ]
