# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0004_match_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='active',
        ),
        migrations.AlterField(
            model_name='match',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
