# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0005_auto_20160411_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='avatar',
            field=models.ImageField(default='', upload_to='avatar'),
            preserve_default=False,
        ),
    ]
