# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0006_player_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='blue_1_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='blue_2_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='red_1_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='red_2_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
